// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package ports

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// NewSubscriber defines model for NewSubscriber.
type NewSubscriber struct {
	// Client Token
	Token string `json:"token"`
}

// SubscribeJSONBody defines parameters for Subscribe.
type SubscribeJSONBody NewSubscriber

// SubscribeJSONRequestBody defines body for Subscribe for application/json ContentType.
type SubscribeJSONRequestBody SubscribeJSONBody
