name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
          files: 'service-account.json'
      env:
          project_id: ${{ secrets.PROJECT_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}
    - uses: azure/docker-login@v1
      with:
        login-server: crpersonalapp.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t crpersonalapp.azurecr.io/jerens-web-api:${{ github.sha }} -f docker/app-prod/Dockerfile
        docker push crpersonalapp.azurecr.io/jerens-web-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-personalwebapi-prod-001'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'crpersonalprod001.azurecr.io/jerens-web-api:${{ github.sha }}'
